# Insurance cost prediction using linear regression

Make a submisson here: https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/assignment/assignment-2-train-your-first-model

In this assignment we're going to use information like a person's age, sex, BMI, no. of children and smoking habit to predict the price of yearly medical bills. This kind of model is useful for insurance companies to determine the yearly insurance premium for a person. The dataset for this problem is taken from [Kaggle](https://www.kaggle.com/mirichoi0218/insurance).


We will create a model with the following steps:
1. Download and explore the dataset
2. Prepare the dataset for training
3. Create a linear regression model
4. Train the model to fit the data
5. Make predictions using the trained model


This assignment builds upon the concepts from the first 2 lessons. It will help to review these Jupyter notebooks:
- PyTorch basics: https://jovian.ai/aakashns/01-pytorch-basics
- Linear Regression: https://jovian.ai/aakashns/02-linear-regression
- Logistic Regression: https://jovian.ai/aakashns/03-logistic-regression
- Linear regression (minimal): https://jovian.ai/aakashns/housing-linear-minimal
- Logistic regression (minimal): https://jovian.ai/aakashns/mnist-logistic-minimal

As you go through this notebook, you will find a **???** in certain places. Your job is to replace the **???** with appropriate code or values, to ensure that the notebook runs properly end-to-end . In some cases, you'll be required to choose some hyperparameters (learning rate, batch size etc.). Try to experiment with the hypeparameters to get the lowest loss.


In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy matplotlib pandas torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy matplotlib pandas torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy matplotlib pandas torch torchvision torchaudio

In [2]:
!pip install jovian

     |████████████████████████████████| 71kB 2.1MB/s 
  Created wheel for uuid: filename=uuid-1.30-cp36-none-any.whl size=6503 sha256=a1e2ca2522ac044f9dd25e93450f7d3f5eed0583a5205c41bc5c5b2c07102880
  Stored in directory: /root/.cache/pip/wheels/2a/80/9b/015026567c29fdffe31d91edbe7ba1b17728db79194fca1f21
Successfully built uuid


In [94]:
import torch
import jovian
import torchvision
import torch.nn as nn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch.nn.functional as F
from torchvision.datasets.utils import download_url
from torch.utils.data import DataLoader, TensorDataset, random_split
from torch.nn.functional import mse_loss

In [47]:
project_name='02-insurance-linear-regression' # will be used by jovian.commit

## Step 1: Download and explore the data

Let us begin by downloading the data. We'll use the `download_url` function from PyTorch to get the data as a CSV (comma-separated values) file. 

In [3]:
DATASET_URL = "https://hub.jovian.ml/wp-content/uploads/2020/05/insurance.csv"
DATA_FILENAME = "insurance.csv"
download_url(DATASET_URL, '.')

To load the dataset into memory, we'll use the `read_csv` function from the `pandas` library. The data will be loaded as a Pandas dataframe. See this short tutorial to learn more: https://data36.com/pandas-tutorial-1-basics-reading-data-files-dataframes-data-selection/

In [4]:
dataframe_raw = pd.read_csv(DATA_FILENAME)
dataframe_raw.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

We're going to do a slight customization of the data, so that you every participant receives a slightly different version of the dataset. Fill in your name below as a string (enter at least 5 characters)

In [5]:
len(dataframe_raw)

1338

In [6]:
your_name = 'subba' # at least 5 characters

The `customize_dataset` function will customize the dataset slightly using your name as a source of random numbers.

In [11]:
rand_str=your_name
int(ord(rand_str[0]))

115

In [12]:
def customize_dataset(dataframe_raw, rand_str):
    dataframe = dataframe_raw.copy(deep=True)
    # drop some rows
    dataframe = dataframe.sample(int(0.95*len(dataframe)), random_state=int(ord(rand_str[0])))
    # scale input
    dataframe.bmi = dataframe.bmi * ord(rand_str[1])/100.
    # scale target
    dataframe.charges = dataframe.charges * ord(rand_str[2])/100.
    # drop column
    if ord(rand_str[3]) % 2 == 1:
        dataframe = dataframe.drop(['region'], axis=1)
    return dataframe
    

In [13]:
dataframe = customize_dataset(dataframe_raw, your_name)
dataframe.head()

age     sex       bmi  children smoker     region      charges
1178   23  female  40.79205         0     no  northeast  2841.499563
1295   20    male  25.74000         1     no  southwest  1925.484400
205    28  female  33.78960         1     no  northeast  4250.980496
1067   39    male  49.90635         0     no  northeast  5642.265181
523    38  female  44.14410         0     no  southeast  5289.664366

Let us answer some basic questions about the dataset. 


**Q: How many rows does the dataset have?**

In [14]:
num_rows = len(dataframe)
print(num_rows)

1271


**Q: How many columns doe the dataset have**

In [15]:
num_cols = len(dataframe.columns)
print(num_cols)

7


**Q: What are the column titles of the input variables?**

In [16]:
input_cols = dataframe.columns.tolist()
print(input_cols)

['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges']


**Q: Which of the input columns are non-numeric or categorial variables ?**

Hint: `sex` is one of them. List the columns that are not numbers.

In [35]:
categorical_cols = dataframe.select_dtypes(exclude=[np.number]).columns.tolist()
print(categorical_cols)

['sex', 'smoker', 'region']


**Q: What are the column titles of output/target variable(s)?**

In [36]:
output_cols = input_cols[-1]
print(output_cols)

charges


**Q: (Optional) What is the minimum, maximum and average value of the `charges` column? Can you show the distribution of values in a graph?**
Use this data visualization cheatsheet for referece: https://jovian.ml/aakashns/dataviz-cheatsheet

In [41]:
print("Minimum Vaue -->",np.min(dataframe['charges']),"Maximum value-->",np.max(dataframe['charges']),"Average value-->",np.average(dataframe['charges']))

Minimum Vaue --> 1099.436422 Maximum value--> 62495.0194498 Average value--> 13049.441789972792


Remember to commit your notebook to Jovian after every step, so that you don't lose your work.

In [42]:
!pip install jovian --upgrade -q

In [43]:
import jovian

In [48]:
# jovian.utils.colab.set_colab_file_id('1H5GTU0idaYMwySZMBlcMhn_kdXP2P0vk')
project_name='02-insurance-linear-regression' # will be used by jovian.commit
jovian.commit(project=project_name)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...


ApiError: ignored

In [44]:
jovian.commit()

[jovian] Detected Colab notebook...


[jovian] Error: Please provide the project argument e.g. jovian.commit(project='my-project')


## Step 2: Prepare the dataset for training

We need to convert the data from the Pandas dataframe into a PyTorch tensors for training. To do this, the first step is to convert it numpy arrays. If you've filled out `input_cols`, `categorial_cols` and `output_cols` correctly, this following function will perform the conversion to numpy arrays.

In [57]:
def dataframe_to_arrays(dataframe):
    # Make a copy of the original dataframe
    dataframe1 = dataframe.copy(deep=True)
    # Convert non-numeric categorical columns to numbers
    for col in categorical_cols:
        dataframe1[col] = dataframe1[col].astype('category').cat.codes
    # Extract input & outupts as numpy arrays
    inputs_array = dataframe1[input_cols].to_numpy()
    targets_array = dataframe1[output_cols].to_numpy()
    return inputs_array, targets_array

Read through the [Pandas documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html) to understand how we're converting categorical variables into numbers.

In [58]:
inputs_array, targets_array = dataframe_to_arrays(dataframe)
inputs_array, targets_array

(array([[2.30000000e+01, 0.00000000e+00, 4.07920500e+01, ...,
         0.00000000e+00, 0.00000000e+00, 2.84149956e+03],
        [2.00000000e+01, 1.00000000e+00, 2.57400000e+01, ...,
         0.00000000e+00, 3.00000000e+00, 1.92548440e+03],
        [2.80000000e+01, 0.00000000e+00, 3.37896000e+01, ...,
         0.00000000e+00, 0.00000000e+00, 4.25098050e+03],
        ...,
        [5.30000000e+01, 0.00000000e+00, 3.12390000e+01, ...,
         0.00000000e+00, 3.00000000e+00, 1.09277644e+04],
        [2.60000000e+01, 1.00000000e+00, 3.16602000e+01, ...,
         1.00000000e+00, 2.00000000e+00, 1.67024746e+04],
        [1.90000000e+01, 0.00000000e+00, 3.31227000e+01, ...,
         1.00000000e+00, 1.00000000e+00, 1.71196042e+04]]),
 array([ 2841.499563,  1925.4844  ,  4250.980496, ..., 10927.7644  ,
        16702.474572, 17119.604222]))

**Q: Convert the numpy arrays `inputs_array` and `targets_array` into PyTorch tensors. Make sure that the data type is `torch.float32`.**

In [76]:
inputs = torch.tensor(inputs_array, dtype=torch.float32)
targets = torch.tensor(targets_array, dtype=torch.float32)

In [77]:
inputs.dtype, targets.dtype

(torch.float32, torch.float32)

Next, we need to create PyTorch datasets & data loaders for training & validation. We'll start by creating a `TensorDataset`.

In [78]:
dataset = TensorDataset(inputs, targets)

**Q: Pick a number between `0.1` and `0.2` to determine the fraction of data that will be used for creating the validation set. Then use `random_split` to create training & validation datasets.**

In [82]:
train_size,val_size,len(dataset)

(1081, 190, 1271)

In [83]:
val_percent = 0.15 # between 0.1 and 0.2
val_size = int(num_rows * val_percent)
train_size = num_rows - val_size


train_ds, val_ds = random_split(dataset,[train_size,val_size]) # Use the random_split function to split dataset into 2 parts of the desired length

Finally, we can create data loaders for training & validation.

**Q: Pick a batch size for the data loader.**

In [85]:
batch_size = 32

In [86]:
train_loader = DataLoader(train_ds, batch_size, shuffle=True)
val_loader = DataLoader(val_ds, batch_size)

Let's look at a batch of data to verify everything is working fine so far.

In [87]:
for xb, yb in train_loader:
    print("inputs:", xb)
    print("targets:", yb)
    break

inputs: tensor([[3.7000e+01, 0.0000e+00, 3.4515e+01, 2.0000e+00, 0.0000e+00, 3.0000e+00,
         6.1857e+03],
        [5.7000e+01, 0.0000e+00, 3.0116e+01, 2.0000e+00, 0.0000e+00, 2.0000e+00,
         1.2377e+04],
        [3.9000e+01, 1.0000e+00, 5.3153e+01, 2.0000e+00, 0.0000e+00, 2.0000e+00,
         6.2291e+03],
        [5.4000e+01, 0.0000e+00, 3.8236e+01, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         1.0705e+04],
        [1.8000e+01, 1.0000e+00, 3.9236e+01, 0.0000e+00, 1.0000e+00, 0.0000e+00,
         3.3925e+04],
        [6.1000e+01, 1.0000e+00, 3.7791e+01, 2.0000e+00, 0.0000e+00, 1.0000e+00,
         1.3837e+04],
        [1.8000e+01, 0.0000e+00, 2.9344e+01, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         2.1525e+03],
        [4.1000e+01, 0.0000e+00, 4.3407e+01, 2.0000e+00, 0.0000e+00, 3.0000e+00,
         7.2243e+03],
        [4.5000e+01, 1.0000e+00, 4.6572e+01, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         7.2994e+03],
        [5.2000e+01, 1.0000e+00, 3.2011e+01, 0.0000e+00, 1.0000e+

Let's save our work by committing to Jovian.

In [88]:
jovian.commit(project=project_name, environment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...


ApiError: ignored

## Step 3: Create a Linear Regression Model

Our model itself is a fairly straightforward linear regression (we'll build more complex models in the next assignment). 


In [89]:
input_size = len(input_cols)
output_size = len(output_cols)
input_size,output_size

(7, 7)

**Q: Complete the class definition below by filling out the constructor (`__init__`), `forward`, `training_step` and `validation_step` methods.**

Hint: Think carefully about picking a good loss fuction (it's not cross entropy). Maybe try 2-3 of them and see which one works best. See https://pytorch.org/docs/stable/nn.functional.html#loss-functions

In [93]:
nn.Linear(input_size,output_size).bias

Parameter containing:
tensor([-0.0092, -0.2262,  0.0887, -0.1411,  0.2428, -0.2865, -0.2857],
       requires_grad=True)

In [95]:
class InsuranceModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(input_size,output_size)                  # fill this (hint: use input_size & output_size defined above)
        
    def forward(self, xb):
        out = self.linear(xb)                          # fill this
        return out
    
    def training_step(self, batch):
        inputs, targets = batch 
        # Generate predictions
        out = self(inputs)          
        # Calcuate loss
        loss = mse_loss(out,targets)                       # fill this
        return loss
    
    def validation_step(self, batch):
        inputs, targets = batch
        # Generate predictions
        out = self(inputs)
        # Calculate loss
        loss = mse_loss(out,targets)                           # fill this    
        return {'val_loss': loss.detach()}
        
    def validation_epoch_end(self, outputs):
        batch_losses = [x['val_loss'] for x in outputs]
        epoch_loss = torch.stack(batch_losses).mean()   # Combine losses
        return {'val_loss': epoch_loss.item()}
    
    def epoch_end(self, epoch, result, num_epochs):
        # Print result every 20th epoch
        if (epoch+1) % 20 == 0 or epoch == num_epochs-1:
            print("Epoch [{}], val_loss: {:.4f}".format(epoch+1, result['val_loss']))

Let us create a model using the `InsuranceModel` class. You may need to come back later and re-run the next cell to reinitialize the model, in case the loss becomes `nan` or `infinity`.

In [103]:
model = InsuranceModel()

Let's check out the weights and biases of the model using `model.parameters`.

In [104]:
list(model.parameters())

[Parameter containing:
 tensor([[-3.0722e-01, -1.6316e-01,  1.5807e-02,  2.0289e-01,  1.6585e-01,
          -1.8692e-01,  2.4254e-01],
         [-3.1387e-01, -1.0870e-01, -1.9275e-01, -3.1823e-01, -3.7139e-01,
           2.4288e-01,  4.2969e-02],
         [-1.1475e-01, -1.7591e-01, -3.4237e-01,  3.7490e-01,  1.8971e-01,
           2.0378e-01, -3.2681e-01],
         [ 7.0277e-02,  2.2209e-01, -2.5556e-01,  1.8854e-01,  2.4594e-01,
           1.8067e-01,  2.8481e-01],
         [ 4.6776e-02, -2.5022e-01, -4.5559e-02,  2.0836e-01, -2.7047e-02,
          -2.0916e-02, -1.5324e-01],
         [ 2.1367e-01,  7.7627e-02, -8.4533e-02,  2.7421e-01,  2.2519e-01,
           1.5220e-04, -2.7894e-01],
         [ 4.8291e-02,  2.4253e-01,  2.7715e-01, -1.4002e-01,  3.0877e-01,
          -9.0386e-02,  2.6572e-01]], requires_grad=True),
 Parameter containing:
 tensor([ 0.3665, -0.0332, -0.3415, -0.0635, -0.1524, -0.3292,  0.0586],
        requires_grad=True)]

One final commit before we train the model.

In [105]:
jovian.commit(project=project_name, environment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...


ApiError: ignored

## Step 4: Train the model to fit the data

To train our model, we'll use the same `fit` function explained in the lecture. That's the benefit of defining a generic training loop - you can use it for any problem.

In [106]:
def evaluate(model, val_loader):
    outputs = [model.validation_step(batch) for batch in val_loader]
    return model.validation_epoch_end(outputs)

def fit(epochs, lr, model, train_loader, val_loader, opt_func=torch.optim.SGD):
    history = []
    optimizer = opt_func(model.parameters(), lr)
    for epoch in range(epochs):
        # Training Phase 
        for batch in train_loader:
            loss = model.training_step(batch)
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()
        # Validation phase
        result = evaluate(model, val_loader)
        model.epoch_end(epoch, result, epochs)
        history.append(result)
    return history

**Q: Use the `evaluate` function to calculate the loss on the validation set before training.**

In [107]:
result = evaluate(model,val_ds) # Use the the evaluate function
print(result)

{'val_loss': 322473664.0}


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:23: UserWarning: Using a target size (torch.Size([])) that is different to the input size (torch.Size([7])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.



We are now ready to train the model. You may need to run the training loop many times, for different number of epochs and with different learning rates, to get a good result. Also, if your loss becomes too large (or `nan`), you may have to re-initialize the model by running the cell `model = InsuranceModel()`. Experiment with this for a while, and try to get to as low a loss as possible.

**Q: Train the model 4-5 times with different learning rates & for different number of epochs.**

Hint: Vary learning rates by orders of 10 (e.g. `1e-2`, `1e-3`, `1e-4`, `1e-5`, `1e-6`) to figure out what works.

In [108]:
epochs = 5
lr = 0.001
history1 = fit(epochs, lr, model, train_loader, val_loader)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:15: UserWarning: Using a target size (torch.Size([32])) that is different to the input size (torch.Size([32, 7])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  from ipykernel import kernelapp as app


RuntimeError: ignored

In [ ]:
epochs = ???
lr = ???
history2 = fit(epochs, lr, model, train_loader, val_loader)

In [ ]:
epochs = ???
lr = ???
history3 = fit(epochs, lr, model, train_loader, val_loader)

In [ ]:
epochs = ???
lr = ???
history4 = fit(epochs, lr, model, train_loader, val_loader)

In [ ]:
epochs = ???
lr = ???
history5 = fit(epochs, lr, model, train_loader, val_loader)

**Q: What is the final validation loss of your model?**

In [ ]:
val_loss = ???

Let's log the final validation loss to Jovian and commit the notebook

In [ ]:
jovian.log_metrics(val_loss=val_loss)

In [ ]:
jovian.commit(project=project_name, environment=None)

Now scroll back up, re-initialize the model, and try different set of values for batch size, number of epochs, learning rate etc. Commit each experiment and use the "Compare" and "View Diff" options on Jovian to compare the different results.

## Step 5: Make predictions using the trained model

**Q: Complete the following function definition to make predictions on a single input**

In [ ]:
def predict_single(input, target, model):
    inputs = input.unsqueeze(0)
    predictions = ???                # fill this
    prediction = predictions[0].detach()
    print("Input:", input)
    print("Target:", target)
    print("Prediction:", prediction)

In [ ]:
input, target = val_ds[0]
predict_single(input, target, model)

In [ ]:
input, target = val_ds[10]
predict_single(input, target, model)

In [ ]:
input, target = val_ds[23]
predict_single(input, target, model)

Are you happy with your model's predictions? Try to improve them further.

## (Optional) Step 6: Try another dataset & blog about it

While this last step is optional for the submission of your assignment, we highly recommend that you do it. Try to replicate this notebook for a different linear regression or logistic regression problem. This will help solidify your understanding, and give you a chance to differentiate the generic patterns in machine learning from problem-specific details.You can use one of these starer notebooks (just change the dataset):

- Linear regression (minimal): https://jovian.ai/aakashns/housing-linear-minimal
- Logistic regression (minimal): https://jovian.ai/aakashns/mnist-logistic-minimal

Here are some sources to find good datasets:

- https://lionbridge.ai/datasets/10-open-datasets-for-linear-regression/
- https://www.kaggle.com/rtatman/datasets-for-regression-analysis
- https://archive.ics.uci.edu/ml/datasets.php?format=&task=reg&att=&area=&numAtt=&numIns=&type=&sort=nameUp&view=table
- https://people.sc.fsu.edu/~jburkardt/datasets/regression/regression.html
- https://archive.ics.uci.edu/ml/datasets/wine+quality
- https://pytorch.org/docs/stable/torchvision/datasets.html

We also recommend that you write a blog about your approach to the problem. Here is a suggested structure for your post (feel free to experiment with it):

- Interesting title & subtitle
- Overview of what the blog covers (which dataset, linear regression or logistic regression, intro to PyTorch)
- Downloading & exploring the data
- Preparing the data for training
- Creating a model using PyTorch
- Training the model to fit the data
- Your thoughts on how to experiment with different hyperparmeters to reduce loss
- Making predictions using the model

As with the previous assignment, you can [embed Juptyer notebook cells & outputs from Jovian](https://medium.com/jovianml/share-and-embed-jupyter-notebooks-online-with-jovian-ml-df709a03064e) into your blog. 

Don't forget to share your work on the forum: https://jovian.ai/forum/t/linear-regression-and-logistic-regression-notebooks-and-blog-posts/14039

In [ ]:
jovian.commit(project=project_name, environment=None)
jovian.commit(project=project_name, environment=None) # try again, kaggle fails sometimes

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/02-insurance-linear-regression" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Committed successfully! https://jovian.ai/aakashns/02-insurance-linear-regression


<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
